-- SYNTHETIC MODEL OUTPUT — not real. Pre-fit SARIMAX(1,0,1)x(1,0,1,7)+dengue
-- forecast (see SYNTHETIC_ARIMAX_VALIDATION.md), computed offline by
-- fit_and_cache_synthetic_forecast.py and read by /forecast as a clearly-labeled
-- stand-in trajectory shape while a facility's real history is still below
-- MIN_DAYS_REQUIRED. Never joined or blended with inventory_snapshots.
CREATE TABLE IF NOT EXISTS synthetic_forecast_cache (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    blood_type text NOT NULL,
    forecast_date date NOT NULL,
    forecast_units numeric NOT NULL,
    model_order text NOT NULL,
    generated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (blood_type, forecast_date)
);

COMMENT ON TABLE synthetic_forecast_cache IS
    'SYNTHETIC MODEL OUTPUT — generated by fit_and_cache_synthetic_forecast.py, not real. Stand-in for /forecast while real facility history is insufficient. See SYNTHETIC_ARIMAX_VALIDATION.md.';
